using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;

namespace FenCalc2.ViewModels;

// Project > Duplicate Floor: pick a source floor (defaults to the current one), a NEW
// unique name (prefilled with the next free floor name, typeable) and how many FLOORS
// to create: windows come from the source floor; area and plan image are inherited
// from the floor below each new copy (same rule as Add Floor); copies 2..N get the
// next free floor names (generated by MainViewModel). The dialog only validates —
// MainViewModel owns the open building and performs each copy, then selects the last
// new floor.
public partial class DuplicateFloorViewModel : ViewModelBase
{
    public DuplicateFloorViewModel(IEnumerable<string> floorNames, string? currentFloor, string nextFreeName)
    {
        foreach (var n in floorNames) SourceFloorNames.Add(n);
        SelectedSourceFloor = currentFloor is not null && SourceFloorNames.Contains(currentFloor)
            ? currentFloor
            : SourceFloorNames.FirstOrDefault();
        NewFloorName = nextFreeName;
    }

    // Storey-ordered names of the open building — the only floors that may be duplicated.
    public ObservableCollection<string> SourceFloorNames { get; } = new();

    [ObservableProperty] private string? _selectedSourceFloor;
    [ObservableProperty] private string _newFloorName = string.Empty;
    [ObservableProperty] private string _copies = "1";
    [ObservableProperty] private string _errorMessage = string.Empty;
    [ObservableProperty] private bool _dialogResult;

    // Set just before DialogResult flips true; MainViewModel copies from it.
    public string? CreatedFloorName { get; private set; }

    // Validated copy count (1..99); only meaningful once DialogResult is true.
    public int CopyCount { get; private set; } = 1;

    partial void OnSelectedSourceFloorChanged(string? value)
    {
        // The name must stay unique against the BUILDING, not the dialog — nothing to do
        // on a source switch, but clear a stale error from a previous attempt.
        ErrorMessage = string.Empty;
    }

    [RelayCommand]
    private void Ok()
    {
        ErrorMessage = string.Empty;

        if (string.IsNullOrEmpty(SelectedSourceFloor))
        {
            ErrorMessage = "Please select the floor to duplicate.";
            return;
        }

        var name = NewFloorName.Trim();
        if (name.Length == 0)
        {
            ErrorMessage = "Enter a name for the new floor.";
            return;
        }

        if (SourceFloorNames.Any(f => string.Equals(f, name, StringComparison.OrdinalIgnoreCase)))
        {
            ErrorMessage = $"A floor named '{name}' already exists.";
            return;
        }

        if (!int.TryParse(Copies.Trim(), out var copies) || copies < 1 || copies > 99)
        {
            ErrorMessage = "Number of copies must be between 1 and 99.";
            return;
        }

        CreatedFloorName = name;
        CopyCount = copies;
        DialogResult = true;
    }

    [RelayCommand]
    private void Cancel()
    {
        DialogResult = false;
    }
}
