using System;
using System.IO;
using System.Reflection;
using Dapper;
using Microsoft.Data.Sqlite;

namespace FenCalc2.Data;

/// <summary>
/// Applies Data/seed/catalogue.sql (embedded in the assembly) to a brand-new database,
/// so someone who downloads the app gets a usable catalogue without owning the old
/// FenCalc install: glazing types, frame materials, climate-zone factors, five window
/// ranges and their window types. Generated by tools/export_seed.py — never edit by hand.
///
/// Runs only when ALL catalogue tables are empty (fresh install). An existing database
/// is never touched: its ranges may have been curated on purpose, and a re-run could
/// resurrect a range the user deliberately deleted.
/// </summary>
public static class CatalogueSeeder
{
    private const string SeedResource = "FenCalc2.Data.seed.catalogue.sql";

    /// <summary>True once per install, right after the seed was applied.</summary>
    public static bool SeededNow { get; private set; }

    public static bool SeedIfEmpty(SqliteConnection conn)
    {
        var ranges = conn.ExecuteScalar<int>("SELECT COUNT(*) FROM WindowRanges");
        var glazing = conn.ExecuteScalar<int>("SELECT COUNT(*) FROM GlazingPerformance");
        var climate = conn.ExecuteScalar<int>("SELECT COUNT(*) FROM ClimateZones");
        if (ranges > 0 || glazing > 0 || climate > 0)
            return false;

        using var stream = Assembly.GetExecutingAssembly().GetManifestResourceStream(SeedResource)
            ?? throw new InvalidOperationException(
                $"Catalogue seed '{SeedResource}' is missing from the build — check the EmbeddedResource in FenCalc2.csproj.");
        using var reader = new StreamReader(stream);

        // Dapper executes the whole batch; SQLite runs the statements in order
        // (ranges before their types, everything OR IGNORE for idempotency).
        conn.Execute(reader.ReadToEnd());

        SeededNow = true;
        return true;
    }
}
