using System;
using System.IO;
using System.Reflection;
using Dapper;
using Microsoft.Data.Sqlite;

namespace FenCalc2.Data;

/// <summary>
/// Applies Data/seed/xa2026.sql (embedded) — the SANS 10400-XA:2026 reference data:
/// table 4 fenestration bands, table 3 shading multipliers and the annex C town rows.
/// The .sql is GENERATED by tools/import_sans2026.py from docs/sans.txt (a local,
/// gitignored extract of the registered standard) — never edit it by hand.
///
/// Unlike CatalogueSeeder this runs on EVERY startup: the statements are idempotent
/// UPSERTs of data that is never user-editable, so corrections and topped-up town rows
/// also reach existing databases (the catalogue's empty-guard would freeze old data
/// forever, which is exactly what we do NOT want here).
/// </summary>
public static class Xa2026Seeder
{
    private const string SeedResource = "FenCalc2.Data.seed.xa2026.sql";

    public static void Apply(SqliteConnection conn)
    {
        using var stream = Assembly.GetExecutingAssembly().GetManifestResourceStream(SeedResource)
            ?? throw new InvalidOperationException(
                $"XA:2026 seed '{SeedResource}' is missing from the build — check the EmbeddedResource in FenCalc2.csproj.");
        using var reader = new StreamReader(stream);

        conn.Execute(reader.ReadToEnd());
    }
}
