#!/usr/bin/env python3
"""Export a curated catalogue seed from a FenCalc2 database into Data/seed/catalogue.sql.

What goes in (deliberately curated — see the KEEP_RANGES / EXCLUDE_TYPES lists):
  * ALL GlazingPerformance rows, ALL WindowFrames rows, ALL ClimateZones rows
  * only the window ranges in KEEP_RANGES, and only their window types
What never goes out: projects, floors, window placements, plan images (your buildings).

Run it against a COPY of the database, never the live one:

    python tools/export_seed.py <scratch-db> [output.sql]

The generated file is embedded into the exe (see FenCalc2.csproj) and applied by
Data/CatalogueSeeder.SeedIfEmpty on a completely fresh install.
"""
from __future__ import annotations

import os
import sqlite3
import sys

# The five ranges published with the app (exact names as stored in WindowRanges).
KEEP_RANGES = [
    "Aluminium Sliding Doors",
    "Aluminium Top Hung",
    "Folding Doors",
    "Side Hung Steel",
    "Top Hung Steel",
]

# Obvious scratch entries inside the kept ranges — left out of the published seed.
EXCLUDE_TYPES = {
    ("Aluminium Top Hung", "test"),
    ("Aluminium Sliding Doors", "sd2"),
}


def q(value) -> str:
    """SQL literal for a value (doubling single quotes; NULL for missing)."""
    if value is None:
        return "NULL"
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, int):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def rows(cur, sql, args=()):
    return list(cur.execute(sql, args))


def main() -> None:
    if len(sys.argv) < 2:
        raise SystemExit(__doc__)
    src = os.path.abspath(sys.argv[1])
    out = os.path.abspath(
        sys.argv[2] if len(sys.argv) > 2
        else os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                          "Data", "seed", "catalogue.sql"))

    con = sqlite3.connect(f"file:{src}?mode=ro", uri=True)
    con.row_factory = sqlite3.Row
    cur = con.cursor()

    present = {r[0] for r in rows(cur, "SELECT WinRange FROM WindowRanges")}
    missing = [r for r in KEEP_RANGES if r not in present]
    if missing:
        raise SystemExit(f"range(s) not found in the source DB: {missing}")

    lines: list[str] = []
    lines.append("-- FenCalc2 catalogue seed, generated by tools/export_seed.py.")
    lines.append("-- Curated: all glazing/frame/climate-zone rows, five window ranges and")
    lines.append("-- their types. Contains NO projects, floors, windows or plan images.")
    lines.append("-- Applied only when a brand-new database has empty catalogue tables")
    lines.append("-- (Data/CatalogueSeeder.SeedIfEmpty), so existing installs never see it.")
    lines.append("")

    lines.append("-- Window ranges (curated subset)")
    for name in KEEP_RANGES:
        lines.append(f"INSERT OR IGNORE INTO WindowRanges (WinRange) VALUES ({q(name)});")
    lines.append("")

    lines.append("-- Glazing performance (complete SANS 10400-XA style table)")
    n = 0
    for r in rows(cur, "SELECT Glass, UValue_Steel, SHGC_Steel, UValue_Other, SHGC_Other "
                       "FROM GlazingPerformance ORDER BY Glass"):
        lines.append("INSERT OR IGNORE INTO GlazingPerformance "
                     "(Glass, UValue_Steel, SHGC_Steel, UValue_Other, SHGC_Other) VALUES "
                     f"({q(r[0])}, {q(r[1])}, {q(r[2])}, {q(r[3])}, {q(r[4])});")
        n += 1
    lines.append(f"-- ({n} rows)")
    lines.append("")

    lines.append("-- Frame materials (complete)")
    n = 0
    for r in rows(cur, "SELECT FrameType FROM WindowFrames ORDER BY FrameType"):
        lines.append(f"INSERT OR IGNORE INTO WindowFrames (FrameType) VALUES ({q(r[0])});")
        n += 1
    lines.append(f"-- ({n} rows)")
    lines.append("")

    lines.append("-- Climate zones: solar exposure factors, zones 1-6 x window-to-floor ratios")
    n = 0
    for r in rows(cur, "SELECT Zone, PH, North, NorthEast, East, SouthEast, South, "
                       "SouthWest, West, NorthWest FROM ClimateZones ORDER BY Zone, PH"):
        lines.append("INSERT OR IGNORE INTO ClimateZones "
                     "(Zone, PH, North, NorthEast, East, SouthEast, South, SouthWest, "
                     f"West, NorthWest) VALUES ({', '.join(q(v) for v in r)});")
        n += 1
    lines.append(f"-- ({n} rows)")
    lines.append("")

    lines.append("-- Window types (curated ranges only)")
    n = 0
    for r in rows(cur, "SELECT WinRange, WinType, WinWidth, WinHeight, WinGlass, WinFrame "
                       "FROM WindowTypes ORDER BY WinRange, WinType"):
        if r[0] not in KEEP_RANGES or (r[0], r[1]) in EXCLUDE_TYPES:
            continue
        lines.append("INSERT OR IGNORE INTO WindowTypes "
                     "(WinRange, WinType, WinWidth, WinHeight, WinGlass, WinFrame) VALUES "
                     f"({', '.join(q(v) for v in r)});")
        n += 1
    lines.append(f"-- ({n} rows)")

    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8", newline="\n") as fp:
        fp.write("\n".join(lines) + "\n")
    con.close()
    print(f"wrote {out} ({os.path.getsize(out)} bytes)")


if __name__ == "__main__":
    main()
